const TransactionsDummyData = [
  {
    id: 1,
    name: 'Tynisha Obey',
    avatar: 'https://xsgames.co/randomusers/assets/avatars/female/1.jpg',
    date: 'Dec 20, 2024 |10:00 AM',
    type: 0,
    amount: 14,
  },
  {
    id: 2,
    name: 'Florencio Dorrance',
    avatar: 'https://xsgames.co/randomusers/assets/avatars/male/2.jpg',
    date: 'Dec 16, 2024 |16:42 PM',
    type: 1,
    amount: 80,
  },
  {
    id: 3,
    name: 'Chantal Shelburne',
    avatar: 'https://xsgames.co/randomusers/assets/avatars/female/3.jpg',
    date: 'Dec 10, 2024 |12:02 AM',
    type: 0,
    amount: 26,
  },
  {
    id: 4,
    name: 'Maryland Winkles',
    phone: '+1-300-555-0161',
    avatar: 'https://xsgames.co/randomusers/assets/avatars/female/4.jpg',
    date: 'Dec 10, 2024 |08:22 AM',
    type: 0,
    amount: 24,
  },
  {
    id: 5,
    name: 'Rodolfo Goode',
    avatar: 'https://xsgames.co/randomusers/assets/avatars/female/5.jpg',
    date: 'Dec 9, 2024 |14:15 PM',
    type: 1,
    amount: 100,
  },
  {
    id: 6,
    name: 'Benny Spanbauer',
    avatar: 'https://xsgames.co/randomusers/assets/avatars/male/6.jpg',
    date: 'Dec 9, 2024 |09:26 AM',
    type: 0,
    amount: 18,
  },
  {
    id: 7,
    name: 'Tyra Dhillon',
    avatar: 'https://xsgames.co/randomusers/assets/avatars/male/7.jpg',
    date: 'Dec 8, 2024 |22:56 PM',
    type: 0,
    amount: 15,
  },
];
export default TransactionsDummyData;
